services:
  - type: web
    name: sentiment-ai
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: MODEL_PATH
        value: /app/models/sentiment_analysis_model_v2.h5
      - key: TOKENIZER_PATH
        value: /app/models/tokenizer_v2.pickle
      - key: MAX_SEQUENCE_LENGTH
        value: 22
