apiVersion: v1
kind: ConfigMap
metadata:
  name: sentiment-ai-config
  labels:
    app: sentiment-ai
data:
  MODEL_PATH: "/app/models/sentiment_analysis_model_v2.h5"
  TOKENIZER_PATH: "/app/models/tokenizer_v2.pickle"
  MAX_SEQUENCE_LENGTH: "22"
